### ISSUE TITLE
Due page development for "/events"

### ISSUE THREAD

**Issue by KrimsonSquad** [CourseKrimson/courseKrimson.github.io#11]
![image](https://github.com/user-attachments/assets/6f43fa0e-3f1d-466e-9a1b-cebf3d6bd865)
The page has not been made/developed yet, think and create one to handle the upcoming events dashboard.

**Comment by shiv-0101** [comment]
Think and create one, from scratch?? Like what have to be added on empty space?

**Comment by KrimsonSquad** [comment]
Yeah, currently you can use dummy events **(must be related with hackathons/hacktoberfest/coding)**.

**Comment by KrimsonSquad** [comment]
Use cards, thumbnails, details, register button and so on for each upcoming event.

**Comment by lade6501** [comment]
Would like work on, is issue still open?

**Comment by shiv-0101** [comment]
@lade6501 all d best dude🙌

**Comment by lade6501** [comment]
Thanks @shiv-0101, can I use any dummy api for `Events Data`.

**Comment by KrimsonSquad** [comment]
Sure, you can use it. We're using dummy images for **course thumbnail** too.

**Comment by shiv-0101** [comment]
> Thanks @shiv-0101, can I use any dummy api for `Events Data`.

Yeah sure...also make sure it's safe.
