### ISSUE TITLE
Due page development for "/programming-languages"

### ISSUE THREAD

**Issue by KrimsonSquad** [CourseKrimson/courseKrimson.github.io#13]
![image](https://github.com/user-attachments/assets/7370bfe1-3c47-4510-84d1-cc918ff362e7)
Develop a page to handle cheatsheets for programming languages.

**Comment by gurshaan17** [comment]
I would like to work on this.
Can you give some details about the content of the page like what should be there

**Comment by KrimsonSquad** [comment]
Develop a page similar to the course [dashboard,](https://github.com/CourseKrimson/courseKrimson.github.io/blob/main/src/pages/Dashboard.jsx)
 which will bring cheatsheets available as cards and then clicking on any cheatsheet card will lead to navigate to the [page](https://github.com/CourseKrimson/courseKrimson.github.io/blob/main/src/pages/Dashboard.jsx) where the cheatsheet in md will be rendered as html.
 --
 You can explore these files:
- [./src/pages/CourseDetail.jsx](https://github.com/CourseKrimson/courseKrimson.github.io/blob/main/src/pages/CourseDetail.jsx)
- [./src/pages/Dashboard.jsx](https://github.com/CourseKrimson/courseKrimson.github.io/blob/main/src/pages/Dashboard.jsx)
- [./src/data/courseData.js](https://github.com/CourseKrimson/courseKrimson.github.io/blob/main/src/data/courseData.js)
- [./public/courses/course1.md](https://github.com/CourseKrimson/courseKrimson.github.io/blob/main/public/courses/course1.md)

**Comment by devsdenepal** [comment]
Yeah, just like that but there should be a dashboard of cheatsheets instead of courses. Built cheatsheet display by taking inspiration from courses.

**Comment by gurshaan17** [comment]
https://github.com/user-attachments/assets/fe0d383b-327a-4860-b891-386ce8808461

**Comment by devsdenepal** [comment]
Good to go!

**Comment by devsdenepal** [comment]
Congrats! PR has been approved, cheatsheets will be updated soon. Thanks for your significant contribution.
