### ISSUE TITLE
Refactor Folder Structure for Better Scalability and Maintenance

### ISSUE THREAD

**Issue by trishan9** [CourseKrimson/courseKrimson.github.io#17]
I have noticed that the current folder structure has all files inside the `src` and `components` folders, which might hinder scalability and maintainability as the project grows. To improve long-term sustainability, I propose refactoring the folder structure by:

- Organizing components based on features and functionality (e.g., `features`, `common`, `utils`, etc.)
- Creating clear separation for styles, hooks, services, and other utilities.
- Structuring files in a way that facilitates easier navigation and code management.

This will make the project more modular and easier for future contributors to understand and maintain. 

I would like to take up this refactoring task and implement the necessary changes. Please let me know your thoughts, and if this aligns with your vision for the project, I would appreciate it if you could assign this issue to me. Looking forward to your feedback!

**Comment by KrimsonSquad** [comment]
Thanks for giving your invaluable time to this project! 
Your approach is correct, and we appreciate **refactoring** the code to properly organize the file and code. We assign this issue to you under _hacktoberfest_

**Comment by trishan9** [comment]
Thanks, I'll make sure the structure is scalable and follows best practices!

**Comment by trishan9** [comment]
I've created the PR for the issue! @KrimsonSquad @devsdenepal
